---
name: Build

on:
  push:
    paths-ignore:
      - ".github/workflows/**"
  workflow_dispatch:
    inputs: {}

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Set up Node
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
          node-version: "18"

      - name: Build
        run: |
          npm ci
          npm run build
