---
name: Lint

on:
  push:
    paths-ignore:
      - ".github/workflows/**"
  workflow_dispatch:
    inputs: {}

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up Node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
          node-version: "18"

      - name: Run linter and spellcheck
        run: |
          npm ci
          npm run lint
          npm run spellcheck
